USERID DOSVS
* $$ JOB JNM=INITDISK,CLASS=0,DISP=D
* $$ LST CLASS=A,DISP=D,JSEP=0
// JOB INITDISK - INITIALIZE 2314 DISK PACK
// ASSGN SYS000,X'130'
// EXEC INTDK
// UID IA,C1
// VTOC STRTADR=(0199000),EXTENT=(20)
VOL1WORK02
// END
/*
/&
* $$ EOJ
